[workspace]
authors = ["llinauer <l.linauer@gmx.at>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "matmul_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025081105,<26"
python = "==3.13"

[pypi-dependencies]
matplotlib = ">=3.10.6, <4"
